# Generated by Django 5.2.15 on 2026-09-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_studentgroup_student_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentgroup',
            options={'ordering': ['name']},
        ),
    ]
