# Generated by Django 6.1.1 on 2026-10-08 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_studentgroup_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('LIVE_STREAM', 'Түз эфир отчету'), ('KAHOOT', 'Каахут отчету')], max_length=20)),
                ('report_date', models.DateField(db_index=True)),
                ('topic', models.CharField(max_length=255)),
                ('event_datetime', models.DateTimeField(blank=True, null=True)),
                ('link', models.URLField(blank=True, default='', max_length=1000)),
                ('summary', models.TextField()),
                ('first_place', models.CharField(blank=True, default='', max_length=255)),
                ('second_place', models.CharField(blank=True, default='', max_length=255)),
                ('third_place', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['report_date', 'created_at'],
            },
        ),
    ]
