# Generated by Django 6.1.1 on 2026-09-10 08:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_rate', models.DecimalField(decimal_places=2, default=150, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Базовая ставка (сом / посещение)')),
                ('online_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Онлайн-бонус (сом / посещение)')),
                ('offline_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Оффлайн-бонус (сом / посещение)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Примечание')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_rate', to=settings.AUTH_USER_MODEL, verbose_name='Ментор')),
            ],
            options={
                'verbose_name': 'Ставка ментора',
                'verbose_name_plural': 'Ставки менторов',
                'ordering': ['mentor__first_name', 'mentor__last_name'],
            },
        ),
    ]
